### ISSUE TITLE
tests for C extensions fail with pypy

### ISSUE THREAD

**Issue by jelmer** [breezy-team/patiencediff#4]
The C extensions have some tests that fail when built for pypy (but not pypy3):

```======================================================================

FAIL: test_matching_blocks (patiencediff.test_patiencediff.TestPatienceDiffLib_c)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "patiencediff/test_patiencediff.py", line 104, in test_matching_blocks
    self.assertDiffBlocks('', '', [])
  File "patiencediff/test_patiencediff.py", line 99, in assertDiffBlocks
    self.assertEqual((len(a), len(b), 0), last)
AssertionError: (0, 0, 0) != None
======================================================================
FAIL: test_matching_blocks_tuples (patiencediff.test_patiencediff.TestPatienceDiffLib_c)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "patiencediff/test_patiencediff.py", line 152, in test_matching_blocks_tuples
    self.assertDiffBlocks([], [], [])
  File "patiencediff/test_patiencediff.py", line 99, in assertDiffBlocks
    self.assertEqual((len(a), len(b), 0), last)
AssertionError: (0, 0, 0) != None
======================================================================
FAIL: test_multiple_ranges (patiencediff.test_patiencediff.TestPatienceDiffLib_c)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "patiencediff/test_patiencediff.py", line 292, in test_multiple_ranges
    [(0, 0, 3), (6, 4, 3), (9, 20, 7)])
  File "patiencediff/test_patiencediff.py", line 99, in assertDiffBlocks
    self.assertEqual((len(a), len(b), 0), last)
AssertionError: (16, 27, 0) != None
```

**Comment by jelmer** [comment]
We've dropped support for pypy (2) so this is now obsolete.
